// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZteeLfiGLrMs3le2qGpDezZwFcvdorg',
    appId: '1:17068021892:web:427dd39b6494b0abd1cad1',
    messagingSenderId: '17068021892',
    projectId: 'plantillaflutterpro',
    authDomain: 'plantillaflutterpro.firebaseapp.com',
    storageBucket: 'plantillaflutterpro.firebasestorage.app',
    measurementId: 'G-E0QXD4BRB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLD9iOcjhIWJZ1YJG7O-0B48v0_BvIA90',
    appId: '1:17068021892:android:6fbc79dbf8beac21d1cad1',
    messagingSenderId: '17068021892',
    projectId: 'plantillaflutterpro',
    storageBucket: 'plantillaflutterpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcfMEVQCVx90_ktBukwvT4VPDyFELSIM',
    appId: '1:17068021892:ios:51cfbd5a56a2e44bd1cad1',
    messagingSenderId: '17068021892',
    projectId: 'plantillaflutterpro',
    storageBucket: 'plantillaflutterpro.firebasestorage.app',
    androidClientId: '17068021892-v9pottp1urktskdhvsf7mqb98f509q18.apps.googleusercontent.com',
    iosClientId: '17068021892-gigshf29mjtvts5sh8ip61tg325qh7lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.autentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcfMEVQCVx90_ktBukwvT4VPDyFELSIM',
    appId: '1:17068021892:ios:51cfbd5a56a2e44bd1cad1',
    messagingSenderId: '17068021892',
    projectId: 'plantillaflutterpro',
    storageBucket: 'plantillaflutterpro.firebasestorage.app',
    androidClientId: '17068021892-v9pottp1urktskdhvsf7mqb98f509q18.apps.googleusercontent.com',
    iosClientId: '17068021892-gigshf29mjtvts5sh8ip61tg325qh7lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.autentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZteeLfiGLrMs3le2qGpDezZwFcvdorg',
    appId: '1:17068021892:web:ec6188405873d624d1cad1',
    messagingSenderId: '17068021892',
    projectId: 'plantillaflutterpro',
    authDomain: 'plantillaflutterpro.firebaseapp.com',
    storageBucket: 'plantillaflutterpro.firebasestorage.app',
    measurementId: 'G-N217TCQDM1',
  );
}
